# Generated by Django 3.1.7 on 2021-03-24 15:51

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='info',
            field=models.JSONField(default=users.models.default_info, null=True),
        ),
    ]
