# Generated by Django 3.1.7 on 2021-03-20 10:36

import blogs.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210320_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='more_info',
            field=models.JSONField(default=blogs.models.default_more_info),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=blogs.models.default_tags, size=None),
        ),
    ]
